// src/components/InventoryItemSelector.vue
<template>
  <Teleport to="body">
    <Transition name="modal-fade" appear>
      <div v-if="visible" class="inventory-item-selector" @click.self="close">
        <Transition name="modal-scale" appear>
          <div class="selector-modal" role="dialog" :aria-label="$t('inventory.selectItem')" aria-modal="true">
            <div class="modal-header">
              <h3>{{ $t("inventory.selectItem") }}</h3>
              <button class="close-btn" @click="close">
                <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                  <path d="M12.5 3.5L3.5 12.5M3.5 3.5L12.5 12.5" stroke="currentColor" stroke-width="1.5"
                    stroke-linecap="round" />
                </svg>
              </button>
            </div>

            <div class="selector-body">
              <div class="modal-toolbar">
                <div class="search-input-wrap">
                  <span class="search-icon" aria-hidden="true">
                    <svg width="16" height="16" viewBox="0 0 16 16" fill="none">
                      <circle cx="7" cy="7" r="4.75" stroke="currentColor" stroke-width="1.5" />
                      <path d="M11 11L14 14" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" />
                    </svg>
                  </span>
                  <input ref="searchInput" v-model="searchQuery" type="text" class="search-input"
                    :placeholder="$t('inventory.searchPlaceholder')" />
                  <button v-if="searchQuery" class="clear-search" type="button" @click="clearSearch"
                    :aria-label="$t('inventory.clearSearch')">
                    <svg width="14" height="14" viewBox="0 0 16 16" fill="none">
                      <path d="M12.5 3.5L3.5 12.5M3.5 3.5L12.5 12.5" stroke="currentColor" stroke-width="1.5"
                        stroke-linecap="round" />
                    </svg>
                  </button>
                </div>
                <div class="toolbar-meta">
                  <span class="result-count">{{
                    $t("inventory.resultCount", {
                      count: filteredItems.length,
                      total: availableItems.length,
                    })
                  }}</span>
                  <span v-if="selectedItemLabel" class="selected-badge">{{
                    $t("inventory.currentSelection", { name: selectedItemLabel })
                  }}</span>
                  <button class="remove-btn" type="button" @click="selectItem(null)">
                    {{ $t("inventory.removeItem") }}
                  </button>
                </div>
              </div>

              <TransitionGroup v-if="filteredItems.length" name="item-appear" appear tag="div" class="items-grid">
                <div v-for="item in filteredItems" :key="item.id" class="item-card"
                  :class="{ selected: selectedItem === item.id }" @click="selectItem(item.id)">
                  <div class="item-image-wrapper">
                    <LazyImage :src="`/icons/ETB_UI/${item.image}`" :alt="getItemName(item.id)"
                      image-class="item-image" />
                  </div>
                  <span class="item-name">{{ getItemName(item.id) }}</span>
                </div>
              </TransitionGroup>
              <div v-else class="empty-state">
                {{ $t("inventory.searchEmpty") }}
              </div>
            </div>
          </div>
        </Transition>
      </div>
    </Transition>
  </Teleport>
</template>

<script>
import LazyImage from "./LazyImage.vue";
import { useI18n } from "vue-i18n";

export default {
  name: "InventoryItemSelector",
  components: {
    LazyImage,
  },
  setup() {
    const { t, te } = useI18n();

    const getItemName = (itemId) => {
      const translationKey = `inventory.items.${itemId}`;
      return te(translationKey) ? t(translationKey) : itemId;
    };

    return {
      getItemName,
    };
  },
  data() {
    return {
      searchQuery: "",
    };
  },
  props: {
    visible: {
      type: Boolean,
      default: false,
    },
    selectedItem: {
      type: String,
      default: null,
    },
  },
  emits: ["update:visible", "select"],
  computed: {
    availableItems() {
      return [
        { id: "AlmondConcentrate", image: "AlmondConcentrate.png" },
        { id: "BugSpray", image: "BugSpray.png" },
        { id: "Camera", image: "Camera.png" },
        { id: "AlmondWater", image: "AlmondWater.png" },
        { id: "Chainsaw", image: "Chainsaw.png" },
        { id: "Crowbar", image: "Crowbar.png" },
        { id: "DivingHelmet", image: "DivingHelmet.png" },
        { id: "EnergyBar", image: "EnergyBar.png" },
        { id: "Firework", image: "Firework.png" },
        { id: "Flaregun", image: "Flaregun.png" },
        { id: "Flashlight", image: "Flashlight.png" },
        { id: "GlowstickBlue", image: "GlowstickBlue.png" },
        { id: "GlowStick", image: "GlowStick.png" },
        { id: "GlowstickRed", image: "GlowstickRed.png" },
        { id: "GlowstickYellow", image: "GlowstickYellow.png" },
        { id: "Knife", image: "Knife.png" },
        { id: "LiquidPain", image: "LiquidPain.png" },
        { id: "Juice", image: "Juice.png" },
        { id: "Rope", image: "Rope.png" },
        { id: "LiDAR", image: "LiDAR.png" },
        { id: "Thermometer", image: "Thermometer.png" },
        { id: "Ticket", image: "Ticket.png" },
        { id: "Toy", image: "Teddy_Bear.png" },
        { id: "WalkieTalkie", image: "WalkieTalkie.png" },
        { id: "MothJelly", image: "MothJelly.png" },
      ];
    },
    filteredItems() {
      const keyword = this.searchQuery.trim().toLowerCase();
      if (!keyword) return this.availableItems;
      return this.availableItems.filter((item) => {
        const itemId = String(item.id || "").toLowerCase();
        const itemName = String(this.getItemName(item.id) || "").toLowerCase();
        return itemId.includes(keyword) || itemName.includes(keyword);
      });
    },
    selectedItemLabel() {
      if (!this.selectedItem) return "";
      return this.getItemName(this.selectedItem);
    },
  },
  watch: {
    visible(isVisible) {
      if (isVisible) {
        this.$nextTick(() => {
          this.$refs.searchInput?.focus?.();
        });
        return;
      }
      this.searchQuery = "";
    },
  },
  methods: {
    close() {
      this.$emit("update:visible", false);
    },
    selectItem(itemId) {
      this.$emit("select", itemId);
      this.close();
    },
    clearSearch() {
      this.searchQuery = "";
      this.$nextTick(() => {
        this.$refs.searchInput?.focus?.();
      });
    },
    handleKeydown(event) {
      if (!this.visible) return;
      if (event.key === "Escape") {
        if (this.searchQuery) {
          this.searchQuery = "";
          event.preventDefault();
          return;
        }
        this.close();
      }
    },
  },
  mounted() {
    window.addEventListener("keydown", this.handleKeydown);
  },
  beforeUnmount() {
    window.removeEventListener("keydown", this.handleKeydown);
  },
};
</script>

<style scoped>
.inventory-item-selector {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 9999;
  backdrop-filter: blur(4px);
  padding: 20px;
  box-sizing: border-box;
  overflow: auto;
}

.selector-modal {
  background: var(--glass-bg);
  backdrop-filter: var(--glass-backdrop-filter);
  -webkit-backdrop-filter: var(--glass-backdrop-filter);
  border: 1px solid var(--glass-border);
  border-radius: 16px;
  box-shadow: 0 8px 32px var(--glass-shadow-light);
  width: 90%;
  max-width: 600px;
  height: min(80vh, 680px);
  overflow: hidden;
  position: relative;
  margin: auto;
  display: flex;
  flex-direction: column;
}

/* 淡入淡出动画 */
.modal-fade-enter-active,
.modal-fade-leave-active {
  transition: opacity 0.3s ease;
}

.modal-fade-enter-from,
.modal-fade-leave-to {
  opacity: 0;
}

/* 缩放动画 */
.modal-scale-enter-active,
.modal-scale-leave-active {
  transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}

.modal-scale-enter-from {
  opacity: 0;
  transform: scale(0.9) translateY(-20px);
}

.modal-scale-leave-to {
  opacity: 0;
  transform: scale(0.9) translateY(20px);
}

/* 物品出现动画 */
.item-appear-enter-active,
.item-appear-leave-active {
  transition: all 0.3s ease;
}

.item-appear-enter-from {
  opacity: 0;
  transform: scale(0.8) translateY(10px);
}

.item-appear-leave-to {
  opacity: 0;
  transform: scale(0.8) translateY(-10px);
}

.item-appear-move {
  transition: transform 0.3s ease;
}

.modal-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 20px 24px;
  border-bottom: 1px solid var(--glass-border);
}

.modal-header h3 {
  margin: 0;
  font-size: 18px;
  font-weight: 600;
  color: var(--text-primary);
}

.close-btn {
  background: none;
  border: none;
  padding: 4px;
  cursor: pointer;
  color: var(--text-secondary);
  transition: color 0.2s ease;
}

.close-btn:hover {
  color: var(--text-primary);
}

.selector-body {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 12px 24px 24px;
  flex: 1;
  min-height: 0;
}

.modal-toolbar {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  align-items: center;
  justify-content: space-between;
}

.search-input-wrap {
  position: relative;
  flex: 1 1 240px;
  min-width: 220px;
}

.search-icon {
  position: absolute;
  left: 12px;
  top: 50%;
  transform: translateY(-50%);
  color: var(--text-secondary);
  pointer-events: none;
}

.search-input {
  width: 100%;
  padding: 10px 36px 10px 36px;
  border: 1px solid var(--glass-border);
  border-radius: 12px;
  background: var(--glass-bg);
  color: var(--text-primary);
  outline: none;
  transition: border-color 0.2s ease, box-shadow 0.2s ease;
}

.search-input::placeholder {
  color: var(--text-secondary);
}

.search-input:focus {
  border-color: var(--accent-color);
  box-shadow: 0 0 0 2px rgba(0, 0, 0, 0.08);
}

.clear-search {
  position: absolute;
  right: 10px;
  top: 50%;
  transform: translateY(-50%);
  border: none;
  background: transparent;
  color: var(--text-secondary);
  cursor: pointer;
  padding: 2px;
}

.clear-search:hover {
  color: var(--text-primary);
}

.toolbar-meta {
  display: flex;
  align-items: center;
  gap: 10px;
  flex-wrap: wrap;
  justify-content: flex-end;
}

.result-count {
  font-size: 12px;
  color: var(--text-secondary);
}

.selected-badge {
  font-size: 12px;
  color: var(--text-primary);
  background: var(--sidebar-active-bg);
  border: 1px solid var(--glass-border);
  padding: 4px 8px;
  border-radius: 999px;
  white-space: nowrap;
}

.remove-btn {
  border: 1px solid rgba(255, 59, 48, 0.3);
  background: rgba(255, 59, 48, 0.1);
  color: var(--error-color);
  padding: 6px 12px;
  border-radius: 10px;
  cursor: pointer;
  transition: background 0.2s ease, border-color 0.2s ease;
  font-size: 12px;
}

.remove-btn:hover {
  background: rgba(255, 59, 48, 0.2);
  border-color: rgba(255, 59, 48, 0.5);
}

.items-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(100px, 1fr));
  grid-auto-rows: max-content;
  gap: 16px;
  overflow-y: auto;
  padding-right: 4px;
  flex: 1;
  min-height: 0;
  align-content: start;
  align-items: start;
}

.item-card {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 12px;
  border: 1px solid var(--glass-border);
  border-radius: 12px;
  cursor: pointer;
  transition: all 0.2s ease;
  background: var(--glass-bg);
}

.item-card:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 16px var(--glass-shadow-light);
}

.item-card.selected {
  border-color: var(--accent-color);
  background: var(--sidebar-active-bg);
}

.item-image-wrapper {
  width: 48px;
  height: 48px;
  margin-bottom: 12px;
  flex-shrink: 0;
}

.item-image {
  width: 48px;
  height: 48px;
  object-fit: contain;
  display: block;
  margin-left: auto;
  margin-right: auto;
}

.item-name {
  font-size: 12px;
  text-align: center;
  color: var(--text-primary);
  line-height: 1.2;
}

.empty-state {
  padding: 28px 12px;
  text-align: center;
  color: var(--text-secondary);
  border: 1px dashed var(--glass-border);
  border-radius: 12px;
  background: var(--glass-bg);
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
}

@media (max-width: 768px) {
  .selector-modal {
    width: 95%;
    margin: 20px;
  }

  .selector-body {
    padding: 12px 16px 20px;
  }

  .search-input-wrap {
    min-width: 100%;
  }

  .toolbar-meta {
    width: 100%;
    justify-content: space-between;
  }

  .items-grid {
    grid-template-columns: repeat(auto-fill, minmax(80px, 1fr));
    gap: 12px;
  }

  .item-image-wrapper {
    width: 40px;
    height: 40px;
  }

  .item-image {
    width: 40px;
    height: 40px;
  }
}
</style>

// src/components/save/InventoryItemSelector.tsx
/**
 * 物品选择器 — 全屏模态、搜索、模糊建议（对应 master InventoryItemSelector）
 */
import { useEffect, useMemo, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { AnimatePresence, motion } from "motion/react";
import { useTranslation } from "react-i18next";
import { Search, X } from "lucide-react";

import { fuzzySearch, type FuzzyMatchResult } from "../../utils/fuzzyMatch";
import { getPinyinTexts } from "../../utils/pinyinMap";
import { LazyImage } from "../ui";
import { cn } from "../../utils";

interface InventoryItem {
  id: string;
  image: string;
}

const AVAILABLE_ITEMS: InventoryItem[] = [
  { id: "AlmondConcentrate", image: "AlmondConcentrate.png" },
  { id: "BugSpray", image: "BugSpray.png" },
  { id: "Camera", image: "Camera.png" },
  { id: "AlmondWater", image: "AlmondWater.png" },
  { id: "Chainsaw", image: "Chainsaw.png" },
  { id: "Crowbar", image: "Crowbar.png" },
  { id: "DivingHelmet", image: "DivingHelmet.png" },
  { id: "EnergyBar", image: "EnergyBar.png" },
  { id: "Firework", image: "Firework.png" },
  { id: "Flaregun", image: "Flaregun.png" },
  { id: "Flashlight", image: "Flashlight.png" },
  { id: "GlowstickBlue", image: "GlowstickBlue.png" },
  { id: "GlowStick", image: "GlowStick.png" },
  { id: "GlowstickRed", image: "GlowstickRed.png" },
  { id: "GlowstickYellow", image: "GlowstickYellow.png" },
  { id: "Knife", image: "Knife.png" },
  { id: "LiquidPain", image: "LiquidPain.png" },
  { id: "Juice", image: "Juice.png" },
  { id: "Rope", image: "Rope.png" },
  { id: "LiDAR", image: "LiDAR.png" },
  { id: "Thermometer", image: "Thermometer.png" },
  { id: "Ticket", image: "Ticket.png" },
  { id: "Toy", image: "Teddy_Bear.png" },
  { id: "WalkieTalkie", image: "WalkieTalkie.png" },
  { id: "MothJelly", image: "MothJelly.png" },
];

/** 物品英文名（模糊匹配多语言兜底，与 en-US/inventory.json 一致） */
const ITEM_ENGLISH_NAMES: Record<string, string> = {
  AlmondConcentrate: "Almond Concentrate",
  BugSpray: "Bug Spray",
  Camera: "Camera",
  AlmondWater: "Almond Water",
  Chainsaw: "Chainsaw",
  Crowbar: "Crowbar",
  DivingHelmet: "Diving Helmet",
  EnergyBar: "Energy Bar",
  Firework: "Firework",
  Flaregun: "Flare Gun",
  Flashlight: "Flashlight",
  GlowstickBlue: "Blue Glow Stick",
  GlowStick: "Green Glow Stick",
  GlowstickRed: "Red Glow Stick",
  GlowstickYellow: "Yellow Glow Stick",
  Knife: "Knife",
  LiquidPain: "Liquid Sorrow",
  Juice: "Juice",
  Rope: "Rope",
  LiDAR: "Scanner",
  Thermometer: "Thermometer",
  Ticket: "Ticket",
  Toy: "Teddy Bear",
  WalkieTalkie: "Walkie Talkie",
  MothJelly: "Moth Jelly",
};

export interface InventoryItemSelectorProps {
  visible: boolean;
  selectedItem: string | null;
  onClose: () => void;
  onSelect: (itemId: string | null) => void;
}

export default function InventoryItemSelector({
  visible,
  selectedItem,
  onClose,
  onSelect,
}: InventoryItemSelectorProps) {
  const { t } = useTranslation();
  const [searchQuery, setSearchQuery] = useState("");
  const searchInputRef = useRef<HTMLInputElement>(null);

  const getItemName = (itemId: string): string => t(`inventory.items.${itemId}`, itemId);

  const filteredItems = useMemo(() => {
    const keyword = searchQuery.trim().toLowerCase();
    if (!keyword) return AVAILABLE_ITEMS;
    return AVAILABLE_ITEMS.filter((item) => {
      const itemId = item.id.toLowerCase();
      const itemName = getItemName(item.id).toLowerCase();
      return itemId.includes(keyword) || itemName.includes(keyword);
    });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [searchQuery, t]);

  const fuzzyResults = useMemo<FuzzyMatchResult<InventoryItem>[]>(() => {
    const keyword = searchQuery.trim();
    if (filteredItems.length > 0 || !keyword) return [];
    return fuzzySearch(
      [keyword],
      AVAILABLE_ITEMS,
      (item) =>
        [
          item.id,
          getItemName(item.id),
          ITEM_ENGLISH_NAMES[item.id] || "",
          ...getPinyinTexts(item.id),
        ].filter(Boolean),
      0.3,
      5
    );
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [searchQuery, filteredItems.length, t]);

  // 打开时聚焦搜索；关闭时重置
  useEffect(() => {
    if (visible) {
      requestAnimationFrame(() => searchInputRef.current?.focus());
    } else {
      setSearchQuery("");
    }
  }, [visible]);

  useEffect(() => {
    const handleKeydown = (event: KeyboardEvent) => {
      if (!visible) return;
      if (event.key === "Escape") {
        if (searchQuery) {
          setSearchQuery("");
          event.preventDefault();
        } else {
          onClose();
        }
      }
    };
    window.addEventListener("keydown", handleKeydown);
    return () => window.removeEventListener("keydown", handleKeydown);
  }, [visible, searchQuery, onClose]);

  const selectItem = (itemId: string | null) => {
    onSelect(itemId);
    onClose();
  };

  const selectedItemLabel = selectedItem ? getItemName(selectedItem) : "";

  return createPortal(
    <AnimatePresence>
      {visible && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          transition={{ duration: 0.2 }}
          onClick={onClose}
          className="fixed inset-0 z-[110] flex items-center justify-center overflow-auto p-5"
          style={{ backgroundColor: "var(--color-bg-overlay)" }}
        >
          <motion.div
            role="dialog"
            aria-modal="true"
            aria-label={t("inventory.selectItem")}
            initial={{ opacity: 0, scale: 0.9, y: -24 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            exit={{ opacity: 0, scale: 0.95, y: 16 }}
            transition={{ duration: 0.22, ease: [0.34, 1.56, 0.64, 1] }}
            onClick={(e) => e.stopPropagation()}
            className="flex h-[min(85vh,720px)] w-[90%] max-w-[640px] flex-col overflow-hidden rounded-2xl border border-[var(--color-border-light)] bg-[var(--color-bg-elevated)] shadow-[0_20px_60px_var(--color-shadow-lg)]"
          >
            <div className="flex items-center justify-between border-b border-[var(--color-border-light)] px-6 py-4">
              <h3 className="text-base font-semibold text-[var(--color-text-primary)]">
                {t("inventory.selectItem")}
              </h3>
              <button
                type="button"
                aria-label={t("common.close")}
                onClick={onClose}
                className="rounded-md p-1.5 text-[var(--color-text-secondary)] transition-all hover:bg-[var(--color-bg-muted)] hover:text-[var(--color-text-primary)]"
              >
                <X size={15} />
              </button>
            </div>

            <div className="flex min-h-0 flex-1 flex-col gap-3.5 px-6 pb-6 pt-4">
              <div className="flex flex-wrap items-center justify-between gap-3">
                <div className="relative min-w-[240px] flex-[1_1_260px]">
                  <Search
                    size={15}
                    className="pointer-events-none absolute left-3.5 top-1/2 -translate-y-1/2 text-[var(--color-text-muted)]"
                  />
                  <input
                    ref={searchInputRef}
                    type="text"
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    placeholder={t("inventory.searchPlaceholder")}
                    className="h-9 w-full rounded-lg border border-[var(--color-border-default)] bg-[var(--color-bg-secondary)] pl-10 pr-9 text-[13px] outline-none transition-all focus:border-[var(--color-border-focus)] focus:ring-2 focus:ring-[var(--color-ring)]"
                  />
                  {searchQuery && (
                    <button
                      type="button"
                      aria-label={t("inventory.clearSearch")}
                      onClick={() => setSearchQuery("")}
                      className="absolute right-2.5 top-1/2 -translate-y-1/2 rounded p-1 text-[var(--color-text-secondary)] hover:text-[var(--color-primary)]"
                    >
                      <X size={13} />
                    </button>
                  )}
                </div>
                <div className="flex flex-wrap items-center justify-end gap-2.5">
                  <span className="text-xs font-medium text-[var(--color-text-secondary)]">
                    {t("inventory.resultCount", {
                      count: filteredItems.length,
                      total: AVAILABLE_ITEMS.length,
                    })}
                  </span>
                  {selectedItemLabel && (
                    <span className="rounded-full border border-[var(--color-border-light)] bg-[var(--color-primary-subtle)] px-2.5 py-1 text-xs font-semibold text-[var(--color-primary)]">
                      {t("inventory.currentSelection", { name: selectedItemLabel })}
                    </span>
                  )}
                  <button
                    type="button"
                    onClick={() => selectItem(null)}
                    className="rounded-lg border border-[var(--color-danger)]/35 bg-[var(--color-danger-subtle)] px-3.5 py-1.5 text-xs font-semibold text-[var(--color-danger)] transition-all hover:brightness-95"
                  >
                    {t("inventory.removeItem")}
                  </button>
                </div>
              </div>

              {filteredItems.length > 0 ? (
                <div className="grid min-h-0 flex-1 grid-cols-[repeat(auto-fill,minmax(100px,1fr))] content-start gap-4 overflow-y-auto pr-1.5">
                  {filteredItems.map((item) => (
                    <button
                      key={item.id}
                      type="button"
                      onClick={() => selectItem(item.id)}
                      className={cn(
                        "flex flex-col items-center rounded-xl border p-3.5 transition-all duration-200",
                        selectedItem === item.id
                          ? "border-[var(--color-primary)] bg-[var(--color-primary-subtle)] shadow-[0_0_0_2px_var(--color-ring)]"
                          : "border-[var(--color-border-light)] bg-[var(--color-bg-secondary)] hover:-translate-y-1 hover:border-[var(--color-border-strong)] hover:shadow-[0_8px_20px_var(--color-shadow)]"
                      )}
                    >
                      <div className="relative z-[1] mb-2.5 h-[50px] w-[50px]">
                        <LazyImage
                          src={`/icons/ETB_UI/${item.image}`}
                          alt={getItemName(item.id)}
                          className="h-full w-full"
                          imageClassName="!object-contain"
                        />
                      </div>
                      <span className="text-xs font-medium leading-tight text-[var(--color-text-primary)]">
                        {getItemName(item.id)}
                      </span>
                    </button>
                  ))}
                </div>
              ) : (
                <div className="flex min-h-0 flex-1 flex-col gap-3.5">
                  <div className="flex flex-1 items-center justify-center rounded-xl border-2 border-dashed border-[var(--color-border-light)] bg-[var(--color-bg-secondary)] px-4 py-8 text-center text-[13px] text-[var(--color-text-secondary)]">
                    {t("inventory.searchEmpty")}
                  </div>
                  {fuzzyResults.length > 0 && (
                    <div className="flex flex-col gap-2.5">
                      <p className="px-1.5 text-xs font-semibold text-[var(--color-text-secondary)]">
                        {t("inventory.didYouMean")}
                      </p>
                      <div className="grid grid-cols-[repeat(auto-fill,minmax(92px,1fr))] gap-3">
                        {fuzzyResults.map((result) => (
                          <button
                            key={result.item.id}
                            type="button"
                            title={`${getItemName(result.item.id)} (${(result.score * 100).toFixed(0)}%)`}
                            onClick={() => selectItem(result.item.id)}
                            className="flex flex-col items-center rounded-xl border border-[var(--color-border-light)] bg-[var(--color-bg-secondary)] p-3 transition-all hover:-translate-y-0.5 hover:border-[var(--color-primary)]"
                          >
                            <div className="mb-2 h-[42px] w-[42px]">
                              <LazyImage
                                src={`/icons/ETB_UI/${result.item.image}`}
                                alt={getItemName(result.item.id)}
                                className="h-full w-full"
                                imageClassName="!object-contain"
                              />
                            </div>
                            <span className="text-[11px] font-medium text-[var(--color-text-primary)]">
                              {getItemName(result.item.id)}
                            </span>
                          </button>
                        ))}
                      </div>
                    </div>
                  )}
                </div>
              )}
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>,
    document.body
  );
}
