// src/components/save/PlayerManager.tsx
/**
 * 玩家列表 — 选择 / 删除 / 添加（创建与编辑共用）
 */
import { useTranslation } from "react-i18next";
import { Trash2, User, UserPlus, Plus } from "lucide-react";

import { cn } from "../../utils";

export interface PlayerRow {
  username?: string | null;
  isOfflinePlayer?: boolean;
  steamId: string;
  sanity?: number;
}

export interface PlayerManagerProps {
  players: PlayerRow[];
  activePlayerIndex: number;
  newSteamId: string;
  playerInputMessage?: string;
  playerInputMessageType?: "success" | "error" | "";
  titleKey?: string;
  emptyHintKey?: string;
  steamIdPlaceholderKey?: string;
  showSanity?: boolean;
  embedded?: boolean;
  showHeader?: boolean;
  showCount?: boolean;
  onNewSteamIdChange: (value: string) => void;
  onAddSteamId: () => void;
  onRemovePlayer: (index: number) => void;
  onSelectPlayer: (index: number) => void;
}

export function getSanityClass(val: number): string {
  if (val >= 80) return "sanity-high";
  if (val >= 50) return "sanity-medium";
  if (val >= 20) return "sanity-low";
  return "sanity-critical";
}

const SANITY_STYLES: Record<string, string> = {
  "sanity-high": "bg-[var(--color-success-subtle)] text-[var(--color-success)]",
  "sanity-medium": "bg-[var(--color-danger-subtle)] text-[#c2820c] dark:text-[#eab308]",
  "sanity-low": "bg-[var(--color-danger-subtle)] text-[var(--color-danger)]",
  "sanity-critical": "bg-[var(--color-danger)]/20 text-[var(--color-danger)]",
};

export default function PlayerManager({
  players,
  activePlayerIndex,
  newSteamId,
  playerInputMessage,
  playerInputMessageType = "",
  titleKey = "editArchive.playerManagement",
  emptyHintKey = "editArchive.noPlayersHint",
  steamIdPlaceholderKey = "editArchive.steamIdPlaceholder",
  showSanity = false,
  embedded = false,
  showHeader = true,
  showCount = true,
  onNewSteamIdChange,
  onAddSteamId,
  onRemovePlayer,
  onSelectPlayer,
}: PlayerManagerProps) {
  const { t } = useTranslation();

  return (
    <div
      className={cn(
        "flex min-h-0 flex-col overflow-hidden rounded-xl border border-[var(--color-border-light)] bg-[var(--color-bg-elevated)]",
        embedded && "border-none bg-transparent"
      )}
    >
      {showHeader && (
        <div className="flex items-center gap-2 border-b border-[var(--color-border-light)] px-4 py-3.5 text-sm font-semibold text-[var(--color-text-primary)]">
          <span>{t(titleKey)}</span>
          {showCount && (
            <span className="ml-auto rounded-full bg-[var(--color-primary)] px-2.5 py-0.5 text-xs font-semibold text-[var(--color-primary-fg)]">
              {players.length}
            </span>
          )}
        </div>
      )}

      {players.length > 0 ? (
        <div className="flex flex-1 flex-col gap-2 overflow-y-auto p-3">
          {players.map((player, index) => {
            const active = activePlayerIndex === index;
            const sanity = player.sanity ?? 100;
            return (
              <div
                key={index}
                role="button"
                tabIndex={0}
                onClick={() => onSelectPlayer(index)}
                onKeyDown={(e) => e.key === "Enter" && onSelectPlayer(index)}
                className={cn(
                  "flex cursor-pointer items-center gap-3 rounded-lg p-3 transition-all duration-150",
                  active
                    ? "bg-[var(--color-primary-subtle)] ring-2 ring-[var(--color-primary)]"
                    : "bg-[var(--color-bg-secondary)] hover:bg-[var(--color-bg-muted)]"
                )}
              >
                <div
                  className={cn(
                    "flex h-9 w-9 shrink-0 items-center justify-center rounded-lg",
                    active
                      ? "bg-[var(--color-primary)] text-[var(--color-primary-fg)]"
                      : "bg-[var(--color-primary-subtle)] text-[var(--color-primary)]"
                  )}
                >
                  <User size={16} />
                </div>
                <div className="flex min-w-0 flex-1 items-center gap-2">
                  <span className="truncate font-semibold text-[var(--color-text-primary)]">
                    {player.username ||
                      (player.isOfflinePlayer
                        ? `${player.steamId}${t("common.localPlayerSuffix")}`
                        : player.steamId)}
                  </span>
                  {showSanity && (
                    <span
                      className={cn(
                        "shrink-0 rounded-full px-2 py-0.5 text-[11px] font-bold",
                        SANITY_STYLES[getSanityClass(sanity)]
                      )}
                    >
                      {sanity}%
                    </span>
                  )}
                </div>
                <button
                  type="button"
                  aria-label={t("common.delete")}
                  onClick={(e) => {
                    e.stopPropagation();
                    onRemovePlayer(index);
                  }}
                  className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md bg-[var(--color-danger-subtle)] text-[var(--color-danger)] transition-colors hover:brightness-95"
                >
                  <Trash2 size={14} />
                </button>
              </div>
            );
          })}
        </div>
      ) : (
        <div className="flex flex-1 flex-col items-center justify-center gap-2.5 p-6 text-center text-[var(--color-text-muted)]">
          <UserPlus size={28} strokeWidth={1.5} className="opacity-50" />
          <p className="text-xs leading-relaxed">{t(emptyHintKey)}</p>
        </div>
      )}

      <div className="flex gap-2.5 border-t border-[var(--color-border-light)] p-4">
        <input
          value={newSteamId}
          type="text"
          placeholder={t(steamIdPlaceholderKey)}
          onChange={(e) => onNewSteamIdChange(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && onAddSteamId()}
          className="h-9 min-w-0 flex-1 rounded-lg border border-[var(--color-border-default)] bg-[var(--color-bg-secondary)] px-3 text-[13px] text-[var(--color-text-primary)] outline-none transition-all placeholder:text-[var(--color-text-muted)] focus:border-[var(--color-border-focus)] focus:ring-2 focus:ring-[var(--color-ring)]"
        />
        <button
          type="button"
          aria-label={t("common.add")}
          onClick={onAddSteamId}
          className="flex h-9 w-10 shrink-0 items-center justify-center rounded-lg bg-[var(--color-primary)] text-[var(--color-primary-fg)] transition-all hover:bg-[var(--color-primary-hover)] active:scale-95"
        >
          <Plus size={16} />
        </button>
      </div>

      {playerInputMessage && (
        <div
          className={cn(
            "mx-4 mb-4 rounded-md px-4 py-2.5 text-[13px]",
            playerInputMessageType === "success"
              ? "bg-[var(--color-success-subtle)] text-[var(--color-success)]"
              : "bg-[var(--color-danger-subtle)] text-[var(--color-danger)]"
          )}
        >
          {playerInputMessage}
        </div>
      )}
    </div>
  );
}

// src/components/PlayerManager.vue
<template>
  <div class="player-list-section" :class="{ embedded }">
    <div v-if="showHeader" class="section-title">
      <span>{{ title }}</span>
      <span v-if="showCount" class="count-badge">{{ players.length }}</span>
    </div>

    <div class="player-list" v-if="players.length > 0">
      <div
        v-for="(player, index) in players"
        :key="index"
        class="player-item"
        :class="{ active: activePlayerIndex === index }"
        @click="$emit('select-player', index)"
      >
        <div class="player-avatar">
          <font-awesome-icon :icon="['fas', 'user']" />
        </div>
        <div class="player-info">
          <span class="player-name">
            {{
              player.username ||
              (player.isOfflinePlayer ? `${player.steamId}(本地)` : player.steamId)
            }}
          </span>
          <span
            v-if="showSanity"
            class="sanity-tag"
            :class="getSanityClass(player.sanity ?? 100)"
          >
            {{ player.sanity ?? 100 }}%
          </span>
        </div>
        <button class="del-btn" @click.stop="$emit('remove-player', index)">
          <font-awesome-icon :icon="['fas', 'trash']" />
        </button>
      </div>
    </div>
    <div class="empty-hint" v-else>
      <font-awesome-icon :icon="['fas', 'user-plus']" />
      <p>{{ emptyHint }}</p>
    </div>

    <div class="add-player-row">
      <input
        :value="newSteamId"
        type="text"
        class="form-input"
        :placeholder="steamIdPlaceholder"
        @input="$emit('update:newSteamId', $event.target.value)"
        @keyup.enter="$emit('add-steam-id')"
      />
      <button class="add-btn" @click="$emit('add-steam-id')">
        <font-awesome-icon :icon="['fas', 'plus']" />
      </button>
    </div>

    <transition name="fade">
      <div
        v-if="playerInputMessage"
        class="msg-tip"
        :class="playerInputMessageType"
      >
        {{ playerInputMessage }}
      </div>
    </transition>
  </div>
</template>

<script setup>
import { computed } from "vue";
import { useI18n } from "vue-i18n";

const props = defineProps({
  players: {
    type: Array,
    default: () => [],
  },
  activePlayerIndex: {
    type: Number,
    default: -1,
  },
  newSteamId: {
    type: String,
    default: "",
  },
  playerInputMessage: {
    type: String,
    default: "",
  },
  playerInputMessageType: {
    type: String,
    default: "",
  },
  titleKey: {
    type: String,
    default: "editArchive.playerManagement",
  },
  emptyHintKey: {
    type: String,
    default: "editArchive.noPlayersHint",
  },
  steamIdPlaceholderKey: {
    type: String,
    default: "editArchive.steamIdPlaceholder",
  },
  showSanity: {
    type: Boolean,
    default: false,
  },
  embedded: {
    type: Boolean,
    default: false,
  },
  showHeader: {
    type: Boolean,
    default: true,
  },
  showCount: {
    type: Boolean,
    default: true,
  },
});

defineEmits(["update:newSteamId", "add-steam-id", "remove-player", "select-player"]);

const { t } = useI18n({ useScope: "global" });

const title = computed(() => t(props.titleKey));
const emptyHint = computed(() => t(props.emptyHintKey));
const steamIdPlaceholder = computed(() => t(props.steamIdPlaceholderKey));

const getSanityClass = (val) => {
  if (val >= 80) return "sanity-high";
  if (val >= 50) return "sanity-medium";
  if (val >= 20) return "sanity-low";
  return "sanity-critical";
};
</script>

<style scoped>
.player-list-section {
  background: var(--card-bg);
  border-radius: 12px;
  border: 1px solid var(--border-color);
  display: flex;
  flex-direction: column;
  min-height: 0;
  overflow: hidden;
}

.player-list-section.embedded {
  background: transparent;
  border: none;
  border-radius: 0;
  overflow: visible;
}

.section-title {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 16px;
  font-size: 14px;
  font-weight: 600;
  color: var(--text-primary);
  border-bottom: 1px solid var(--border-color);
}

.count-badge {
  margin-left: auto;
  background: var(--primary);
  color: white;
  padding: 2px 10px;
  border-radius: 12px;
  font-size: 12px;
}

.player-list {
  flex: 1;
  overflow-y: auto;
  padding: 12px;
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.player-item {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 12px;
  border-radius: 10px;
  background: var(--bg-secondary);
  cursor: pointer;
  transition: all 0.15s;
}

.player-item:hover {
  background: var(--hover-bg);
}

.player-item.active {
  background: rgba(0, 122, 255, 0.1);
  outline: 2px solid var(--primary);
}

.player-avatar {
  width: 36px;
  height: 36px;
  border-radius: 8px;
  background: rgba(0, 122, 255, 0.12);
  color: var(--primary);
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

.player-info {
  display: flex;
  align-items: center;
  gap: 8px;
  flex: 1;
  min-width: 0;
}

.player-name {
  font-weight: 600;
  color: var(--text-primary);
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.sanity-tag {
  font-size: 12px;
  padding: 2px 8px;
  border-radius: 999px;
  font-weight: 700;
}

.sanity-high {
  background: rgba(34, 197, 94, 0.12);
  color: var(--success-color);
}

.sanity-medium {
  background: rgba(245, 158, 11, 0.12);
  color: var(--warning-color);
}

.sanity-low {
  background: rgba(239, 68, 68, 0.12);
  color: var(--error-color);
}

.sanity-critical {
  background: rgba(239, 68, 68, 0.2);
  color: var(--error-color);
}

.del-btn {
  width: 32px;
  height: 32px;
  border-radius: 10px;
  border: none;
  background: rgba(239, 68, 68, 0.12);
  color: var(--error-color);
  cursor: pointer;
  transition: all 0.2s;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}

.del-btn:hover {
  background: rgba(239, 68, 68, 0.2);
}

.empty-hint {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 10px;
  padding: 24px;
  color: var(--text-tertiary);
  text-align: center;
}

.add-player-row {
  display: flex;
  gap: 10px;
  padding: 16px;
  border-top: 1px solid var(--border-color);
}

.form-input {
  flex: 1;
  padding: 12px 14px;
  font-size: 14px;
  border: 1px solid var(--border-color);
  border-radius: 10px;
  background: var(--bg-secondary);
  color: var(--text-primary);
  outline: none;
}

.add-btn {
  width: 44px;
  border: none;
  border-radius: 10px;
  background: var(--primary);
  color: white;
  cursor: pointer;
}

.msg-tip {
  padding: 10px 16px;
  margin: 0 16px 16px;
  border-radius: 10px;
  font-size: 13px;
}

.msg-tip.success {
  background: rgba(34, 197, 94, 0.12);
  color: var(--success-color);
}

.msg-tip.error {
  background: rgba(239, 68, 68, 0.12);
  color: var(--error-color);
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.2s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}
</style>
